### ISSUE TITLE
Can not compile

### ISSUE THREAD

**Issue by sv1** [xynium/PNPropag#1]
$ make
gcc -Wall  -g  -O0 -D_GNU_SOURCE  `pkg-config --cflags gtk+-3.0` PNPropag.c CartoPropag.c  -o PNPropag  `pkg-config --libs gtk+-3.0`   -lm 
PNPropag.c: In function ‘motion_notify_event_cb’:
PNPropag.c:206:7: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
       for (int it=0 ; it<iNStat;it++){ //Calc la distance des stations po trouver la + pres
       ^
PNPropag.c:206:7: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
CartoPropag.c: In function ‘Init’:
CartoPropag.c:196:4: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
    for (int it=0;it<ird; it++) {
    ^
CartoPropag.c:196:4: note: use option -std=c99, -std=gnu99, -std=c11 or -std=gnu11 to compile your code
CartoPropag.c:256:17: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
                 for (int itmp=0;itmp<strlen(strCarteFile);itmp++){
                 ^
CartoPropag.c: In function ‘PlotAllStat’:
CartoPropag.c:684:5: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
     for (int it= 0; it<iNStat;it++){
     ^
CartoPropag.c: In function ‘PlotPropag’:
CartoPropag.c:858:8: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
        for (int ii=0; ii<NPTS-1;ii++){  // repere l'echelle
        ^
CartoPropag.c:859:10: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
          for (int jj=0; jj<NPTS-1;jj++){
          ^
CartoPropag.c:867:16: error: redefinition of ‘ii’
       for (int ii=1; ii<NPTS-1;ii++){
                ^
CartoPropag.c:858:17: note: previous definition of ‘ii’ was here
        for (int ii=0; ii<NPTS-1;ii++){  // repere l'echelle
                 ^
CartoPropag.c:867:7: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
       for (int ii=1; ii<NPTS-1;ii++){
       ^
CartoPropag.c:868:10: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
          for (int jj=1; jj<NPTS-1;jj++){
          ^
CartoPropag.c: In function ‘PlotForStat’:
CartoPropag.c:1074:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNline;i++ ) { //carroyage ordonn�e
             ^
CartoPropag.c:1080:22: error: redefinition of ‘i’
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1074:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNline;i++ ) { //carroyage ordonn�e
                      ^
CartoPropag.c:1080:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNcol;i++){  //abssice
             ^
CartoPropag.c:1088:22: error: redefinition of ‘i’
             for (int i = 0; i < 24; i++) {
                      ^
CartoPropag.c:1080:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1088:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i = 0; i < 24; i++) {
             ^
CartoPropag.c:1103:22: error: redefinition of ‘i’
             for (int i=0;i<iNline;i++ ) { //valeur ordonn�e
                      ^
CartoPropag.c:1088:22: note: previous definition of ‘i’ was here
             for (int i = 0; i < 24; i++) {
                      ^
CartoPropag.c:1103:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<iNline;i++ ) { //valeur ordonn�e
             ^
CartoPropag.c:1109:22: error: redefinition of ‘i’
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1103:22: note: previous definition of ‘i’ was here
             for (int i=0;i<iNline;i++ ) { //valeur ordonn�e
                      ^
CartoPropag.c:1109:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNcol;i++){  //abssice
             ^
CartoPropag.c:1127:22: error: redefinition of ‘i’
             for (int i = 0; i < 24; i++) { //trace les pts SNR
                      ^
CartoPropag.c:1109:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1127:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i = 0; i < 24; i++) { //trace les pts SNR
             ^
CartoPropag.c:1144:22: error: redefinition of ‘i’
             for (int i=0;i<=iNline;i++ ) { //carroyage  //ordonn�e
                      ^
CartoPropag.c:1127:22: note: previous definition of ‘i’ was here
             for (int i = 0; i < 24; i++) { //trace les pts SNR
                      ^
CartoPropag.c:1144:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNline;i++ ) { //carroyage  //ordonn�e
             ^
CartoPropag.c:1150:22: error: redefinition of ‘i’
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1144:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNline;i++ ) { //carroyage  //ordonn�e
                      ^
CartoPropag.c:1150:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNcol;i++){  //abssice
             ^
CartoPropag.c:1161:22: error: redefinition of ‘i’
             for (int i=0;i<=iNline;i++ ) { //valeur ordonn�e
                      ^
CartoPropag.c:1150:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1161:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNline;i++ ) { //valeur ordonn�e
             ^
CartoPropag.c:1167:22: error: redefinition of ‘i’
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1161:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNline;i++ ) { //valeur ordonn�e
                      ^
CartoPropag.c:1167:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i=0;i<=iNcol;i++){  //abssice
             ^
CartoPropag.c:1186:22: error: redefinition of ‘i’
             for (int i = 0; i < 24; i++) { //trace les pts  Rel
                      ^
CartoPropag.c:1167:22: note: previous definition of ‘i’ was here
             for (int i=0;i<=iNcol;i++){  //abssice
                      ^
CartoPropag.c:1186:13: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
             for (int i = 0; i < 24; i++) { //trace les pts  Rel
             ^
Makefile:11: recipe for target 'all' failed
make: *** [all] Error 1

**Comment by xynium** [comment]
Add -std=c99 in makefile
Corrected
